### ISSUE TITLE
CssLayout undesired whitespace

### ISSUE THREAD

**Issue by nezajem** [henrikerola/FlexibleOptionGroup#7]
When one of parent layouts of a FlexibleOptionGroupItemComponent is a Csslayout, an undesired whitespace under that CssLayout occurs. It vanishes after anything in the layout is clicked.

Edit: Just realized this is probably a general issue of CssLayout added into a heavier layout, my apologies.

**Comment by henrikerola** [comment]
Based on the edited message, I am closing this. If still problems, please reopen.
